### ISSUE TITLE
Site-wide classifier?

### ISSUE THREAD

**Issue by joaoribeirovaz** [Perlkonig/grav-plugin-classifier#1]
Is it possible to add site-wide classes to tags (from content and from templates)?

My use case is adding a class to every link / anchor element.

**Comment by Perlkonig** [comment]
Not currently, no. Usually it's simple enough to add class designations directly in the template. If I have some time, I'll look at how I could accommodate.

**Comment by joaoribeirovaz** [comment]
You are right. I also believe applying a class to every element of a type
is out of scope of your plugin.

(I’m testing a css framework that establishes no base styling for links, so
every link should be styled with a custom class. Trying to solve this is
how I found your plugin)

Great job. I’ll keep watching. Thanks
